version: "3.8"

services:
  worker-backup:
    build: .
    container_name: mongo_backup_worker
    environment:
      MONGO_HOST: "mongodb-yourfinaces" 
      MONGO_PORT: "27017"
      MONGO_USER: " your-finances"
      MONGO_PASSWORD: "yourFinances123"
      MONGO_DB: "admin"
      BACKUP_DIR: "/backups"
      ZIP_PASSWORD: "senha123"
      BUCKET_NAME: "backup-mongo-58ba42be"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/service-account.json"
    volumes:
      - ./backups:/backups
    networks:
      - test-latency-configuration_mongo-db-network	
    restart: always

networks:
  test-latency-configuration_mongo-db-network :
    external: true  
